/**
 * 등록된 화면 경로 목록 — 메뉴 관리 화면의 「화면 경로」 드롭다운이 쓴다.
 * 직접 입력을 막아 사이드바에 죽은 링크가 생길 길을 없앤다.
 *
 * App.jsx가 아니라 별도 모듈인 이유는 순환 import 때문이다 —
 * App이 화면을 import하고 그 화면이 다시 App을 import하게 된다.
 * <b>App.jsx에 라우트를 더하면 여기에도 더한다</b>(경로 변수 :id가 붙은 수정 경로는 뺀다 —
 * 메뉴가 가리킬 자리가 아니다).
 */
export const ROUTE_PATHS = [
    '/',
    '/monitoring/worker',
    '/oms/inbound-order',
    '/oms/inbound-orders',
    '/oms/ato-odr',
    '/oms/outbound-order',
    '/oms/outbound-orders',
    '/inbound/asn',
    '/inbound/receiving',
    '/inbound/putaway-order',
    '/inbound/putaway',
    '/inbound/confirm',
    '/stock/status',
    '/stock/history',
    '/stock/attribute',
    '/stock/lot-change',
    '/stock/hold',
    '/stock/move',
    '/stock/spmt',
    '/stock/count',
    '/stock/adjust',
    '/outbound/order',
    '/outbound/wave',
    '/outbound/allocation',
    '/outbound/pick-order',
    '/outbound/replenishment',
    '/outbound/picking',
    '/outbound/shipping',
    '/master/prod',
    '/master/uom',
    '/master/zone',
    '/master/location',
    '/master/fxng-loc',
    '/master/prod-vndr',
    '/master/vendor',
    '/master/store',
    '/master/nbr-rules',
    '/master/codes',
    '/master/usr',
    '/master/labels',
    '/master/menu',
    '/master/menu-auth',
    '/strategy/inspection',
    '/strategy/putaway',
    '/strategy/wave',
    '/strategy/allocation',
    '/m',
    '/m/receiving',
    '/m/putaway',
    '/m/stock-inquiry',
    '/m/stock-move',
    '/m/stock-count',
    '/m/replenishment',
    '/m/picking',
    '/m/shipping',
];
